### ISSUE TITLE
Support for golang lambda

### ISSUE THREAD

**Issue by stefanopallicca-imagicle** [aws-observability/aws-otel-lambda#101]
From the documentation, it looks like it is not possible (yet?) to use otel with golang.

I would like to be able to use Otel like in other languages, or a better documentation (as, for example, the one existing for .net runtime.

**Describe alternatives you've considered**
aws sdk to push traces to xray, but no support for sdk v2 yet on that front sent me back here.

**Comment by lupengamzn** [comment]
Hi @stefanopallicca-imagicle ,

Thanks for the inquiry

We're currently working on OTel's support for Lambda golang. Please stay tuned and come back later to check.

Thanks

**Comment by cyrille-leclerc** [comment]
Hello,
According to the dashboard [Roadmap - AWS Distro for OpenTelemetry](https://github.com/orgs/aws-observability/projects/4), the support of Lambda Go Functions is already available as we see "July Release (Done): Go support for Lambda".

However, I can't find documentation and the [aws-otel-lambda CHANGELOG.md](https://github.com/aws-observability/aws-otel-lambda/blob/main/CHANGELOG.md) suggests no Lambda layer for Otel Golang was released.

Can we get visibility on the availability of the support of Lambda Go functions?
