### ISSUE TITLE
Add more 3rd party Collector exporters and processors to lambdaComponent module

### ISSUE THREAD

**Issue by wangzlei** [aws-observability/aws-otel-lambda#104]
**Is your feature request related to a problem? Please describe.**
Before [opentelemetry-lambda CNCF account ](https://github.com/open-telemetry/community/issues/685)is available, aws-observability is the only OTel Lambda layer provider. In term of meeting more user's expectation we want to support as more 3rd party components as possible, as long as the layer size does not get inflated too much and meet Amazon security requirement.

**Describe the solution you'd like**
[All collector components in ADOT Collector](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/defaultcomponents/defaults.go#L19-L44) have passed Amazon security check, ADOT Lambda Collector extension can include these exporters and processors. But make sure that:
1. check the layer size and Lambda memory consumption, don't increase too much than before.
2. add corresponding integration test in CI/CD.

It is hard to verify end-to-end result for 3rd party exporter, a compromised option is just enable these exporters in Lambda to see if Collector extension get started successfully.

**Describe alternatives you've considered**
N/A

**Additional context**
ADOT Lambda components module in https://github.com/aws-observability/aws-otel-collector/tree/main/pkg/lambdacomponents

**Comment by kolanos** [comment]
@wangzlei Can getting to parity [with the upstream](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go) be an achievable near term goal?
