### ISSUE TITLE
Support for OTEL_PROPAGATORS other than awsxray

### ISSUE THREAD

**Issue by michaelhyatt** [aws-observability/aws-otel-lambda#109]
**Is your feature request related to a problem? Please describe.**
At the moment, Python lambdas only support AWS-XRay trace propagation. Setting `OTEL_PROPAGATORS` environment variable to anything than `awsxray` is ignored.

**Describe the solution you'd like**
Support for other context propagators, such as W3C and B3 by setting `OTEL_PROPAGATORS=tracecontext`, for example.

**Describe alternatives you've considered**
I managed to get it to work with `tracecontext` by cloning the `otel-instrumentation` script, adding `environ["OTEL_PROPAGATORS"] = "tracecontext"` and setting `AWS_LAMBDA_EXEC_WRAPPER` env variable to it.

**Comment by anuraaga** [comment]
Thanks @michaelhyatt - agree that we should check for the presence of the variable before overwriting it like we do in other languages
