### ISSUE TITLE
[Python] Lambda Layer is not found

### ISSUE THREAD

**Issue by ghost** [aws-observability/aws-otel-lambda#133]
[According to the docs](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python#add-the-arn-of-the-lambda-layer), the lambda ARN for US-East-1 should be `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python38-ver-1-3-0:1`, however this results in the following error when clicking "verify":

```
Failed to load layer version details: The resource you requested does not exist. (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 427b8941-9073-48ed-8598-febe07d5ff5c; Proxy: null)
```

Is there a list anywhere of the actual versions of this layer, or will I need to manually try incrementing the version number?

**Comment by wangzlei** [comment]
Checking the canary test for python layer in us-east-1, the layer arn is correct.
https://github.com/aws-observability/aws-otel-lambda/blob/main/sample-apps/python-aws-sdk-aiohttp-terraform/layer.tf#L15

May I know how do you verify the layer? and please make sure your client is in the same region.

**Comment by vasireddy99** [comment]
Closing this Issue, based on the response from @wangzlei and the python layer is available in `us-east-1`. Please re-open this issue if needed.
