### ISSUE TITLE
Java Agent Lambda Layer Not Sending all Traces

### ISSUE THREAD

**Issue by otj202** [aws-observability/aws-otel-lambda#135]
I have a Spring application running on lambda. I have configured the Java autoinstrumentation layer (and found that it only works with Java 11). I have found that about 1/3 - 1/2 of the traces being sent to XRay are incomplete. Specifically, some of the requests show the full trace of the request, down to calling my DynamoDB instance, whereas some of them only show the invocation/overhead of invoking the lambda function. Note that the invocation/overhead traces are tracked simply by enabling XRay Tracing in the Lambda console, so in these cases the Agent is essentially sending nothing at all to Xray. My question is, why is it failing almost half the time?

**Comment by anuraaga** [comment]
Hi @otj202 - that isn't expected behavior indeed if you haven't reconfigured the sampler. Can you try enabling debug logging `-Dotel.javaagent.debug=true` to see if there are any errors logged?

https://github.com/open-telemetry/opentelemetry-java-instrumentation#troubleshooting

**Comment by otj202** [comment]
Hey, I dont think I can pass a system property because i'm running on lambda. can i set an environment variable to do this?

**Comment by anuraaga** [comment]
@otj202 Ah yeah, then you can do `OTEL_JAVAAGENT_DEBUG=true`

**Comment by otj202** [comment]
Im getting this error:
```
java.lang.ClassNotFoundException: io.grpc.netty.NettyChannelProvider
```

**Comment by otj202** [comment]
any progress on this? I've just been using the XRAY sdk in the mean time, but would prefer to use this .
