### ISSUE TITLE
In case of disabled AWS Tracing (X-ray) spans are not sent

### ISSUE THREAD

**Issue by mat-rumian** [aws-observability/aws-otel-lambda#14]
**Description:**
I've instrumented Python Lambda with ADOT instrumentation but I've deactivated the AWS Xray Tracing.
I'm invoking Lambda from the AWS Console (test invoke). I can see in the logs **_X_AMZN_TRACE_ID = "Root=1-605a3357-3fdb2ab603403e7e1dcdfb10;Parent=783f1fb448fc1be2;Sampled=0"** so I assume trace/span was generated but was not exported to the collector. I've discovered when **Sampled=0** then traces/spans are not exported.

What's the right way to export spans in case of disabled AWS X-Ray (Tracing) or/and invoke without context propagation?

**Comment by wangzlei** [comment]
Thanks for raising this question, right now we don't support `export spans in case of disabled AWS X-Ray (Tracing) or/and invoke without context propagation`.

AWS Lambda and XRay integration has been designed to use one flag `Active tracing` to control both sample and export to XRay. Before supporting OTel in Lambda, the traces are only able to be exported to XRay so we haven't had confusion. Now we need reconsider the use case customer want to enable tracing but not export to XRay by default.

**Comment by mat-rumian** [comment]
I think we can close this issue. Setting `OTEL_TRACES_SAMPLER=always_on` is solving the problem.
