### ISSUE TITLE
Only run smoke tests for released layer

### ISSUE THREAD

**Issue by willarmiros** [aws-observability/aws-otel-lambda#143]
Today, in the [release workflow](https://github.com/aws-observability/aws-otel-lambda/blob/main/.github/workflows/release.yml), we run a smoke test after making any public release. We test for the layer's presence in all regions and run a quick test to validate it. However we do this for *each* layer in *each* region, which is problematic because:

1. It couples failures for one layer type to release workflows for all layers
2. This is wasteful & causes the workflows to be very long, and scale linearly with the amount of layer types.

We should only run directly impacted groups of smoke tests per release.

**Comment by NathanielRN** [comment]
Closing because #149 was merged and the latest release worked successfully.
