### ISSUE TITLE
NodeJS 12.x environment support for auto instrumentation

### ISSUE THREAD

**Issue by csmuthukuda** [aws-observability/aws-otel-lambda#18]
we have a graphQL API written in nodeJS and hosted in AWS Lambda. We are currently considering using AWS OTEL to enable observability in our API, but as I can see, this lambda layer is only supporting python, or am I missing something here. Is there any way I can use this in our environment?

**Comment by wangzlei** [comment]
Hi, 
Thanks for your attention. ADOT NodeJS Lambda support is in process, we have finished [Lambda instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/399), and part of [sample application](https://github.com/open-telemetry/opentelemetry-lambda/tree/main/nodejs) in upstream Repo. Will release ADOT NodeJS public Lambda layer and corresponding sample application in aws-observability/aws-otel-lambda soon.

**Comment by wangzlei** [comment]
Hi, we have released AWS managed lambda layer for ADOT JavaScript SDK and ADOT collector. please check [README](https://github.com/aws-observability/aws-otel-lambda/blob/main/README.md)

**Comment by csmuthukuda** [comment]
@wangzlei Thanks a lot for all the hard work..will check it out.
