### ISSUE TITLE
Having trouble building layer and Java app

### ISSUE THREAD

**Issue by CeeBeeCee** [aws-observability/aws-otel-lambda#20]
Hi!

I'm trying to build the ADOT layer and deploy the sample Java Lambda as per your guide https://github.com/aws-observability/aws-otel-lambda/tree/main/sample-apps/java-lambda. In Step 4, you have :

cd sample-apps/java-lambda
run.sh

Here, I'm getting this exception. Any ideas why?

```
_FAILURE: Build failed with an exception.

* Where:
Build file '/home/ec2-user/aws-otel-lambda/sample-apps/java-lambda/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating root project 'spark-sample-app'.
> Could not find method testCompile() for arguments [{group=junit, name=junit, version=4.12}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDep
endencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org_
```

I'm building this on an EC2 running Amazon Linux.

Thanks
--Sib

**Comment by anuraaga** [comment]
Hi @CeeBeeCee - sorry for the confusion. To be honest I'm a bit confused too :) We're currently working on Java lambda layers here

https://github.com/open-telemetry/opentelemetry-lambda/tree/main/java

I'm not too sure what this sample app here is for but I think we'll be removing it once and cleaning up docs here to point to that work. If you can wait a bit we'll have something, though you can play with what's in that repo too.

**Comment by CeeBeeCee** [comment]
No problems @anuraaga . I will play around with the project in the link you sent.
