### ISSUE TITLE
Add opentelemetry-instrumentation-logging library to the python layer to allow logs/traces correlation

### ISSUE THREAD

**Issue by rcooper85** [aws-observability/aws-otel-lambda#202]
I have a python lambda function that is being auto-instrumented using the lambda layer aws-otel-python38-ver-1-7-1. This is working fine, however, I need to get the lambda function to log the traceid into the CloudWatch logs. One way of doing this is to use the opentelemetry-intrumentation-logging python library. As I am instrumenting both the lambda traces and logs to an elastic cluster, I want to be able to correlate the traces with the logs. 

The aws-otel-python38-ver-1-7-1 layer does not appear to have the opentelemetry-instrumentation-logging in the requirements.txt. As a workaround I could create my own layer but I think it's important that you allow everyone to have access to this logging library as correlation is an important part of Observability.

**Comment by NathanielRN** [comment]
Spoke with the team internally, and we decided it would make sense to add this `logging` package to the upstream https://github.com/open-telemetry/opentelemetry-lambda/ repo in the requirements.
