### ISSUE TITLE
[nodejs] tracer.startSpan() occasionally returns non-recording span with aws-otel-nodejs 1.0 layer

### ISSUE THREAD

**Issue by simonmarshall** [aws-observability/aws-otel-lambda#203]
### Description
 
We use the aws-otel-nodejs version 1.0 layer with our node lambdas to create Open Telemetry span events.
We have observed that, occasionally, telemetry does not make it to Honeycomb for a lambda invocation.
We have noticed that, when this happens:

- The Span returned by the tracer's startSpan() method is a NonRecordingSpan object.

- Telemetry is typically fine for invocations of the lambda before and after that lambda invocation, seemingly within the same lambda container.
 
We are able to reproduce this issue with a cut-down lambda that takes an event of records, and uses a simple otel wrapper to create a span for each record and add an event for that record.  The lambda is triggered by an SQS queue, to which we stream large numbers of messages (via a producer lambda) to make it easy to see the issue.  It's not quite the same as with our normal setup, where messages stream intermittently, but the issue symptoms are the same.

Our tracer is obtained on each invocation of the lambda by:
  `const tracer = otelApi.trace.getTracer('fof-1852-logger');`
And our otel wrapper does the following with that `tracer` when creating a span for a particular string `message`:
```
    let span: Span | undefined;
    try {
      const name = message.split('\n')[0];
      span = this.tracer.startSpan(`${level} : ${name}`);
      try {
        // log span state for monitoring purposes, to see if recording
        console.info(`startSpan isRecording=${span.isRecording()} spanContext=${JSON.stringify(span.spanContext())} message="${message} span=${JSON.stringify(span)}"`);
      } catch (e) {
        // note the non-first spans within the lambda invocation have recursive structure, when recording
        console.info(`startSpan isRecording=${span.isRecording()} spanContext=${JSON.stringify(span.spanContext())} message="${message} span=${e}"`);
      }
      span.addEvent(name, {
        level,
        message,
      });
    } catch (error) {
      console.error(`Error adding event: ${error}`);
      console[level.toLowerCase() as keyof Omit<Console, 'Console'>](message);
    } finally {
      if (span !== undefined) {
        span.end();
      }
    }
```
We see in CloudWatch that some invocations of the lambda log `startSpan isRecording=false` (and with `spanContext={traceFlags: 0, ...}`) and these naturally do not make it to Honeycomb.

However, it is difficult to debug this further and understand the cause.

Please find attached a more detailed description of the issue, steps to recreate it using the attached lambda code, and an example of the issue when it occurs.

[tracer occasionally returns non-recording span.pdf](https://github.com/aws-observability/aws-otel-lambda/files/7854459/tracer.occasionally.returns.non-recording.span.pdf)
[fof-1852-logger.zip](https://github.com/aws-observability/aws-otel-lambda/files/7854463/fof-1852-logger.zip)
[fof-1852-producer.zip](https://github.com/aws-observability/aws-otel-lambda/files/7854464/fof-1852-producer.zip)

**Comment by simonmarshall** [comment]
I should've mentioned I have enabled debug logging in collector.yaml.
Attached is the effect when the otel span created via the layer tracer is of the non-recording vs recording  type.

As you can see, logging from the layer is missing when the otel span created via the layer tracer is of the non-recording type.
![fof-1852-isRecording=false-cw](https://user-images.githubusercontent.com/26903735/149320490-dc70966a-5a1b-4541-990d-84ca84736563.png)

Extra logging appears in CloudWatch when the otel span created via the layer tracer is of the recording type.
![fof-1852-isRecording=true-cw](https://user-images.githubusercontent.com/26903735/149320434-e5f1bcb4-2e1e-438e-b7a0-0f7fbc5f4ebb.png)

I guess this isn't a surprise, but I should've mentioned it!

**Comment by NathanielRN** [comment]
Hi thanks for your issue! In the follow up to this issue here https://github.com/open-telemetry/opentelemetry-lambda/issues/201, the poster said these are the same issues. I thought it best to consolidate the issues and move the discussion to that one if that's okay with you?

Thanks for your through deep dive! The PDF is excellent for understanding your issue. I will be referencing them in that issue above.

**Comment by simonmarshall** [comment]
Hi @NathanielRN - yes we're part of the same team, and I'm the one who raised the same issue with aws support that I believe you're also aware of, so it's fine to consolidate them.

**Comment by NathanielRN** [comment]
@simonmarshall In the last 2 pictures you posted, could you expand the logs for the `isRecording=` lines? I was hoping to see what the `spanContext` was when those logs were sent.

**Comment by simonmarshall** [comment]
Hi @NathanielRN, there are examples expanded in the pdf, does that have the info you need?

**Comment by NathanielRN** [comment]
Sorry for the delay in response @Ancient-Dragon, but in short yes, I believe this `;Sampled=0` would have a large effect as I mentioned in the other issue https://github.com/open-telemetry/opentelemetry-lambda/issues/201. Posted my findings and suggested solution there.

Thanks @simonmarshall I found the information I was looking for!

**Comment by NathanielRN** [comment]
Closing because we solved it in https://github.com/open-telemetry/opentelemetry-lambda/issues/201.

Lambda has a default sampling rate of 5% which cannot be changed.

Instead, we _can_ change the OTel Sampler to ALWAYS sample so we get traces.
