### ISSUE TITLE
OTel not showing DynamoDb, SQS and other services nodes in AWS x-ray service map for Quarkus Java Native Builds

### ISSUE THREAD

**Issue by sharma-dheeraj-pfg** [aws-observability/aws-otel-lambda#207]
**OTel with Quarkus Lambda Native Images**
We are using java with Quarkus framework to build lambda workloads, but after enabling OTel, we only get the invoke and shutdown trace. There is no other service node or traces found in logs or in xray, even though multiple aws services are being invoked from this lambda.
![image](https://user-images.githubusercontent.com/77103248/151339451-ebd8643f-f5fe-4c30-8818-9160940ca3a2.png)

**OTel must detect and display nodes in Xray service map for native images**
![image](https://user-images.githubusercontent.com/77103248/151340368-c84a4e96-00e3-4c4b-91af-d3c898002f57.png)
We want OTel to report the full picture of Lambda lifecycle, including Overhead and Initialization, and traces of other services invoked.
It does well in Java environments, But when we moved to native build of Quarkus to get rid of initialization delays, its not reporting everything.

**Additional context**
We are using Java 11 with [quarkus lambda](https://quarkus.io/guides/amazon-lambda) in native mode.
We have configured OTEL using lambda layer, [Lambda Java Auto Instrumentation](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java-auto-instr)
Also tried running OTel in debug mode setting OTEL_JAVAAGENT_DEBUG=true, but that didn't gave us enough information to resolve this issue with other aws services.

**Comment by wangzlei** [comment]
Javaagent does not work for native image, and Lambda java auto instrumentation layer actually embeds an opentelemetry javaagent. Please track the thread https://github.com/open-telemetry/opentelemetry-java-contrib/issues/156
