### ISSUE TITLE
Support for Custom Runtime

### ISSUE THREAD

**Issue by cw-kajiwara** [aws-observability/aws-otel-lambda#219]
Hello. Thank you for providing such a nice lambda layer.
I'm using custom runtime for my lambda function (in Rust), and now would like to trace the app via OpenTelemetry.
After I looked around this repo, I ended up not finding any way to use ADOT for custom runtime. 
It would be helpful if this lambda layer could support custom runtime.

**Comment by anuraaga** [comment]
Hi @cw-kajiwara - ADOT doesn't currently support rust, but it supports Go applications using a custom runtime - essentially the lambda layer only contains a telemetry collector but the app needs to have instrumentation built in due to the lack of auto instrumentation. This will be the same for Rust.

The docs for ADOT Lambda Go and OpenTelemetry rust may be able to get you started.
https://aws-otel.github.io/docs/getting-started/lambda/lambda-go#lambda-layer
https://docs.rs/opentelemetry/latest/opentelemetry/

**Comment by cw-kajiwara** [comment]
Hi @anuraaga. Thank you very much for your guidance!

As you taught me, adding `aws-otel-collector-amd64-ver-0-43-1:1` to my lambda function worked for me! 
I saw the spans sent from my application appeared in log 👍

**Comment by ymwjbxxq** [comment]
Hello all,

I tried using the "aws-otel-collector-arm64-ver-0-56-0"
I can see my spans in CloudWatch but I am pretty sure I miss something because I don't see any span in x-ray

```
fn init_tracer() -> sdkTracer {
    global::set_text_map_propagator(XrayPropagator::

    // Install stdout exporter pipeline to be able to retrieve the e collected spans.
    // For the demonstration, use `Sampler::AlwaysOn` sampler to sample all traces. In a production
    // application, use `Sampler::ParentBased` or `Sampler::TraceIdRatioBased` with a desired ratio.
    stdout::new_pipeline()
        .with_trace_config(
            config()
                .with_sampler(Sampler::AlwaysOn)
                .with_id_generator(XrayIdGenerator::default()),
        )
        .install_simple()
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let tracer = init_tracer();
    
    tracing_subscriber::fmt()
        .with_ansi(false)
        .without_time()
        .with_max_level(tracing_subscriber::filter::LevelFilter::INFO)
        .init();

    let config = aws_config::load_from_env().await;
    let dynamodb_client = aws_sdk_dynamodb::Client::new(&config);

    // other stuff

    lambda_http::run(service_fn(|event: Request| {
      tracer.in_span("root", |cx| {
           my_handler(event, cx)
      })
    })).await?;
   
    global::shutdown_tracer_provider();
    Ok(())
}

pub async fn my_handler(event: Request, ctx: Context) -> Result<impl IntoResponse, Error> {
   ctx.span().add_event("calling dyanmodb", vec![]);
  //dynamodb query
  ctx.spaIt).add_event("doing something else", vec![]);
}
```

it is possible to see a working example that maybe instrument one of the aws services? (like DynamoDB).
