### ISSUE TITLE
[ERROR] UnboundLocalError: local variable 'span_kind' referenced before assignment

### ISSUE THREAD

**Issue by M3gar00** [aws-observability/aws-otel-lambda#238]
Issue Type: Bug

I get the following error when I attempt to run a lambda with the `aws-otel-lambda` layer activated. The ARN of the layer is: `arn:aws:lambda:${var.aws_region}:901920570463:layer:aws-otel-python38-amd64-ver-1-9-1:2`

The full error message I get is:
```
[ERROR] UnboundLocalError: local variable 'span_kind' referenced before assignment
Traceback (most recent call last):
  File "/opt/python/wrapt/wrappers.py", line 578, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/opt/python/opentelemetry/instrumentation/aws_lambda/__init__.py", line 203, in _instrumented_lambda_handler_call
    kind=span_kind,
```

**Comment by bryan-aguilar** [comment]
Could you provide any additional code example?

**Comment by M3gar00** [comment]
I'm not sure what code example I can provide; I do not have access to the code from which this error is being emitted. I used AWS resources to implement this as an [Auto-Instrumented](https://aws-otel.github.io/docs/getting-started/python-sdk/trace-auto-instr) layer on my Lambda application.

**Comment by sungwonh** [comment]
This issue is resolved, but not released yet.
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/926

**Comment by juanitosvq** [comment]
Hi @vasireddy99, looks like `v0.30b1` of `opentelemetry-python-contrib` is already available. Any plans on releasing a new layer with the fix for this? Thanks!

**Comment by vasireddy99** [comment]
Hi @juanitosvq , The lambda layers with this fix are expected to be available around may 13th. shall provide more updates as we go on.

**Comment by M3gar00** [comment]
@vasireddy99 -- It looks like the fix is not yet in for this. Am I missing something?

**Comment by vasireddy99** [comment]
HI @M3gar00, Please expect the fix to be available with the new lambda layers which are expected to release in this month.

**Comment by vasireddy99** [comment]
Update : The lambda Layer with OTel python `1.11.1` that includes the fix for this issue is available.

**Comment by TriQuach** [comment]
@vasireddy99 The new OTel lambda layer is working from our side, and the problem has been fixed! Thanks for fixing the issue :+1:
