### ISSUE TITLE
Python Lambda layer sends duplicate spans

### ISSUE THREAD

**Issue by ericksoen** [aws-observability/aws-otel-lambda#249]
**Is your feature request related to a problem? Please describe.**

We see duplicate spans from our auto-instrumented Lambda Layer and have confirmed the behavior with multiple vendor backends.

![Honeycomb duplicate span graph](https://user-images.githubusercontent.com/28688013/168457731-bfc3e0eb-64d5-49fa-a93d-ba28a7e6f34f.png)

![Honeycomb raw span data](https://user-images.githubusercontent.com/28688013/168457677-d7995840-634c-4ae4-9ee4-4d5ae0b5afd8.png)

![New Relic raw span data](https://user-images.githubusercontent.com/28688013/168457716-587ef2a4-0bba-4638-b72e-72c7be3e4a86.png)

Our Lambda configuration is as follows:

```txt
Layer version: arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python38-amd64-ver-1-9-1:1
Memory size: 2048 mb
Timeout: 50 s
Runtime: Python 3.8
Architecture: x86_64
```

It took a while to cut down to the most minimal, reproducible example to share here (our actual application code has more complexity like network requests occurring on background threads that we pass a `Context` object to in order to correctly link).

I had assumed that complexity was contributing to the duplicate spans that we periodically see, but I think this example indicates that is not the case 

```python
import json
import os
import random
from opentelemetry import trace
import requests

# Initialize to an OpenTelemetry tracer
tracer = trace.get_tracer(__name__)
REQUEST_URL = 'https://domain.com'

def lambda_handler(event, context):
    print(f"The tracer type = {type(tracer)}")

    requests.get(REQUEST_URL)
    
    body = {
        'statusCode': 200,
        'statusDescription': '200 OK',
        'isBase64Encoded': False,
        'headers': {
            'Content-Type': "application/json"
        },
        'body': json.dumps({"functionName": os.getenv('AWS_LAMBDA_FUNCTION_NAME', '')})
    }
    return body
```

**Describe the solution you'd like**
Duplicate spans are not sent. Note: this behavior does not occur on all traces.

**Describe alternatives you've considered**
Continue to operate with the duplicate behavior as is. It's a bit of an inconvenience for our developers since it artificially increases the span count on some UI views and we've previously gotten good insight from questions like "What are the traces doing with the highest # of spans?"

**Additional context**

1. I have validated the duplicate behavior with both `gRPC` and `http` exporters
2. I have validated that the behavior exists with multiple enterprise vendors (Honeycomb and New Relic) from the screen shots above
3. The duplicate span behavior does not occur with the logging exporter
4. I have observed the duplicate span behavior with memory limits as low as 256 MB and as high as 4096 MB (our actual function configuration uses 2048).

**Comment by ericksoen** [comment]
UPDATE: Adding some [additional assets](https://gist.github.com/ericksoen/61530e3682acbf6a58df6a8888186169) to help reproduce the issue. 

NOTE: I feel like I have to be missing something obvious at this point.

**Comment by TriQuach** [comment]
We're experiencing the same issue. Please let us know if the problem has been fixed. Thank you very much!

**Comment by TriQuach** [comment]
We're still facing the same issue with version 1.15.0. Just wondering if this issue has been fixed?
