### ISSUE TITLE
No Processors available

### ISSUE THREAD

**Issue by garymartyn** [aws-observability/aws-otel-lambda#269]
**Is your feature request related to a problem? Please describe.**
Hi all, 
We are looking to use the **ResourceProcessor** but no processors are available: https://github.com/aws-observability/aws-otel-lambda#adot-lambda-layer-available-components

**Describe the solution you'd like**
Enable each processor from https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor.
Or is there any reason that they are not available?

**Describe alternatives you've considered**
Switching to https://github.com/open-telemetry/opentelemetry-lambda/

**Comment by bryan-aguilar** [comment]
Due to the constraints of lambda environments the choice of included components has been restricted. If you need further processors after collection we recommend exporting the data to another collector service.
