### ISSUE TITLE
Failure to export from collector to backend (GO Lambda Layer)

### ISSUE THREAD

**Issue by itaybaror** [aws-observability/aws-otel-lambda#271]
I have been attempting to instrument lambdas using the docs on the ADOT website. I have successfully instrumented some python lambdas, where they send the data to the collector, and then exports the data to lightstep (my backend). However when i try to instrument in go, i do see the logs in cloudwatch (i configured the collector to send data to lightstep and to logs) but when it tries to export the data to lightstep (and i have tried other backends) i am usually greeted with some sort of grpc or timeout error, and i do not see the data in the backend. 

I have attached pictures with the errors i receive. Keep in mind that with my working python implementation i am using the same collector config file.

Errors:
<img width="1426" alt="Screen Shot 2022-07-25 at 10 04 16 AM" src="https://user-images.githubusercontent.com/107562167/180797738-5e691af1-5139-40bb-a51b-e9b674b2df10.png">

<img width="1313" alt="Screen Shot 2022-07-25 at 10 12 26 AM" src="https://user-images.githubusercontent.com/107562167/180797956-6ff8b557-ac0a-4b16-82f2-28730b6a7652.png">

My collector config file:
<img width="1051" alt="Screen Shot 2022-07-25 at 10 11 41 AM" src="https://user-images.githubusercontent.com/107562167/180797823-88927d34-3129-4bfd-9d06-9c3cbf2bf4e8.png">

**Comment by jangaraj** [comment]
You are using wrong exporter. Lightstep doesn't support OTLP GRPC, only OTLP HTTP - https://docs.lightstep.com/docs/send-otlp-over-http-to-lightstep

Correct exporter config should be:
```
  otlphttp:
    traces_endpoint: https://ingest.lightstep.com/traces/otlp/v0.9
    headers:
        'Lightstep-Access-Token': 'YOUR-LIGHTSTEP-ACCESS-TOKEN-HERE'
 ```

**Comment by itaybaror** [comment]
@jangaraj Are you sure? i have seen in multiple places that oltp grpc should work. For example on the ADOT documentation...
https://aws-otel.github.io/docs/components/otlp-exporter#lightstep


![Screen Shot 2022-07-26 at 2 14 02 PM](https://user-images.githubusercontent.com/107562167/181081218-846ecdd4-a86c-443f-b2b4-396206299f52.png)

**Comment by jangaraj** [comment]
I'm sure. I would believe vendor doc in this case. Ask your Lightstep support.

**Comment by itaybaror** [comment]
Also i get the about the same error when i try to configure olthttp
![Screen Shot 2022-07-26 at 2 32 47 PM](https://user-images.githubusercontent.com/107562167/181084718-0f280f39-5cad-4028-acec-305f33a5865f.png)

**Comment by jangaraj** [comment]
I guess you don't have network connectivity (sec. group, network acl, NAT,...) to public LS collector from your Lambda.

**Comment by austinlparker** [comment]
FYI, OTLP GRPC works to Lightstep. `ingest.lightstep.com:443` in the Collector config works fine. It's strange that it would work from your Python Lambda but not your Go one, the only thing I can think would be on the AWS side, but if your two Lambdas are in the same security group and have the same ACLs and NAT and whatnot, then I'm kind of at a loss.

**Comment by stephenhong** [comment]
Are there any updates to this issue? I'm experiencing something similar where my lambda functions work fine with otel lambda layers (Java, Node.js, Python) but fails to export traces with the Go lambda layer
