### ISSUE TITLE
Feature request: Kinesis exporter

### ISSUE THREAD

**Issue by nickcox** [aws-observability/aws-otel-lambda#298]
Would you consider including the [Kinesis exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awskinesisexporter)? This seems like a good option for people looking for a low latency buffer for telemetry before further processing it or exporting downstream.

**Comment by mhausenblas** [comment]
Thanks a lot for this @nickcox! Do you have a concrete use case or is this more like a general suggestion?

**Comment by nickcox** [comment]
Apologies @mhausenblas, I completely missed your reply.

Yes, we would like to compare latency of exporting to Kinesis (and using Firehose w/ out of the box buffering) vs the [currently buggy](https://github.com/aws-observability/aws-otel-lambda/issues/229) and high latency otlp exporter.

**Comment by Aneurysm9** [comment]
The OTLP exporter is not the source of latency or defects and changing to the Kinesis exporter would not affect the behavior described in the linked issue.  We are preparing a new release that includes https://github.com/open-telemetry/opentelemetry-lambda/pull/310/ which we expect to resolve the linked issue.

**Comment by nickcox** [comment]
aiui, the design of the lambda collector is that it exports each batch synchronously and therefore the latency depends on the latency of the downstream system.

Our observability platform seems to have a typical latency of 250 to 1000ms. I'm pretty sure we could do better than that by exporting to Kinesis and then processing those events asynchronously. Open to other suggestions too though.
