### ISSUE TITLE
Publish layer to more regions

### ISSUE THREAD

**Issue by DewaldDeJager** [aws-observability/aws-otel-lambda#299]
**Is your feature request related to a problem? Please describe.**
I can't use the official layer in my Lambda functions because it is not published in the `af-south-1` region. The problem is even worse for the ARM64 layer as it is published to fewer regions

**Describe the solution you'd like**
1. Publish the official AMD64 layer to these regions:
  - af-south-1
  - eu-south-1
2. Publish the official ARM64 layer to these regions:
  - us-west-1
  - eu-west-3
  - eu-north-1
  - eu-south-1
  - ca-central-1
  - af-south-1
  - sa-east-1

**Describe alternatives you've considered**
1. Build from source and publish as a custom layer
2. Publish a copy of an official layer in another region as a custom layer in the desired region

To publish a copy of the official layer as a custom layer:
1. Get the S3 URL for the custom layer
  1. Get the ARN for the custom layer in a supported region
    - AMD64: `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-6-0:1`
    - ARM64: `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-arm64-ver-1-6-0:1`
  2. Get the S3 URL for the layer: `aws --region us-east-1 lambda get-layer-version-by-arn --arn <arn> --query Content.Location --output text`
  3. Download the layer: `curl -o layer.zip <url>`
  4. Publish the layer in your own account in the desired region: `aws --region <desired-region> lambda publish-layer-version --layer-name "aws-otel-nodejs-<arch>" --compatible-runtimes nodejs12.x nodejs14.x nodejs16.x --compatible-architectures <arch> --zip-file fileb://layer.zip`

**Comment by garyzhuosim** [comment]
Is it possible to publish layer to `cn-north-1` region also?

**Comment by vasireddy99** [comment]
Thank you for creating this issue, we are currently working to support more regions and shall update the correspondence here with any developments.
