### ISSUE TITLE
ADOT Lambda Canaries are failing

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-lambda#301]
https://github.com/aws-observability/aws-otel-lambda/actions/workflows/canary.yml

Lambdas Canary workflows are failing during the destroy step. This is leaving with an excess of resources in the account under test. This includes IAM Roles, APIGW, IAM Policies

**Comment by bryan-aguilar** [comment]
Disabled Canary workflow to prevent resource blockage within test account.

**Comment by Kausik-A** [comment]
Canaries are [green](https://github.com/aws-observability/aws-otel-lambda/actions/runs/3175861445) now. Closing this issue
