### ISSUE TITLE
Support for Lambda Telemtry API

### ISSUE THREAD

**Issue by dale-vendia** [aws-observability/aws-otel-lambda#379]
**Is your feature request related to a problem? Please describe.**
As far as I'm aware it is not easy to correlate a lambda function error with a particular trace. From what I understand the Lambda Telemetry API solves this problem.

Is there a plan to support it? https://aws.amazon.com/blogs/compute/introducing-the-aws-lambda-telemetry-api/

**Comment by mhausenblas** [comment]
ADOT PM here. We currently do not have plans to provide direct support for the Lambda Telemetry API but I'm interested to learn about use cases, if anyone can share details?

**Comment by RichiCoder1** [comment]
@mhausenblas I was mostly interested just for the phase events so one could potentially get more insight into the lambda lifecycle. In addition, being able to send logs via the standard function stdout was interesting.

That said, I'd expect both to be toggleable behaviors for the automatic instrumentation/collector that runs w/ Lambdas.
