### ISSUE TITLE
Java Lambda triggered through API Gateway is not continuing a trace rather it starts a new trace

### ISSUE THREAD

**Issue by Sutty100** [aws-observability/aws-otel-lambda#392]
**Describe the bug**
A Java 11 Corretto Lambda receiving a request through API Gateway does not continue the parent trace. The lambda starts a new trace ignoring the fact it has been called by another service that has already initiated a trace.

For example I have Spring Boot Service A -> API Gateway -> Lambda B
I have also tried Lambda A -> API Gateway -> Lambda B both behave the same

The trace collected in Elastic APM (or Zipkin, basically I think anything that isn't XRAY) captures each service as its own distinct trace. If I just have two spring boot applications then the trace is correctly captured.

**Steps to reproduce**
Create a local spring boot service that makes a http call to a Lambda through API Gateway.

**What did you expect to see?**
A single trace starting in Service A, showing the http request and linking this to Service B

**What did you see instead?**
No link and two separate traces 

**Environment**
The Lambda is using the following layer: arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-amd64-ver-1-19-2:1

The Spring Boot service is using the latest AWS OTEL version (as of today) downloaded from here: https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr

**Comment by Aneurysm9** [comment]
Can you provide some additional details?  It would be helpful to have debug logs from your collector instance, including with the `logging` exporter at the detailed/debug level.

**Comment by Sutty100** [comment]
Sure. I've zipped up the logs from both lambdas which includes the applications logs and also the openTel logging. I've also included the logs of stand alone collector there both pushing to. I have also included the config for the 2 lambdas and the standalone collector
[Archive.zip](https://github.com/aws-observability/aws-otel-lambda/files/10438046/Archive.zip)

**Comment by rapphil** [comment]
@Sutty100 can you make sure that the call that is performed from Lambda A to Lambda B is performed using a library that supports auto instrumentation? We recommend using the Okhttp library https://square.github.io/okhttp/

**Comment by rapphil** [comment]
Marking the issue as stale was we are strongly suspecting that the problem is the usage of an library that does not support auto-instrumentation, which would lead to having two trace ids.

**Comment by rapphil** [comment]
The issue might not be the library to perform the http calls. I will update this ticket soon with findings. I'm suspecting about the auto-instrumentation library not being able to identify all the type of lambda handler types for java (Stream vs event based handlers).
