### ISSUE TITLE
Node ESM handler used with layer does not capture.

### ISSUE THREAD

**Issue by JamesKyburz** [aws-observability/aws-otel-lambda#416]
Lambda layer doesn't support ESM handlers?

When following the guide here https://aws-otel.github.io/docs/getting-started/lambda/lambda-js, then the x-ray trace only contains network and SDK calls if the lambda handler is CommonJS.

The same code but in a ESM handler had no network and SDK call traces.

**Comment by Aneurysm9** [comment]
ECMAScript Modules are not presently supported by OTel-JS.  Follow [this issue](https://github.com/open-telemetry/opentelemetry-js/issues/1946) for updates there.  Once the issue is resolved upstream we will ensure that both handler types can be used with the Lambda layer.
