### ISSUE TITLE
Create integration tests for Amazon Managed Prometheus 

### ISSUE THREAD

**Issue by rapphil** [aws-observability/aws-otel-lambda#537]
**Is your feature request related to a problem? Please describe.**

We need to be confident that our lambda layers are working correctly with Amazon Managed Prometheus. Therefore we should add integration tests that continuously validate that.

**Describe the solution you'd like**
Add integration tests for all supported layers:

- [x] Java Agent
- [ ] Java Wrapper
- [ ] NodeJS
- [ ] Python
- [ ] DotNet/Go

**Comment by vsakaram** [comment]
Java agent lambda layer pipeline is available now to test with AMP
