### ISSUE TITLE
[AWS Lambda Java]Unable to see the traces and logs

### ISSUE THREAD

**Issue by pradeepkusingh** [aws-observability/aws-otel-lambda#595]
**Describe the bug**
I have followed the instruction and build a lambda in java, added Layer. I am http collector. Enabled logging and seeing everything is ready but my collector is not receiving any data, I am unable to debug.

 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/opentelemetry-collector.yaml'
receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  logging:
    loglevel: debug
  otlphttp:
    endpoint: https://abcd:4817
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/otlphttp] 
extensions:
  health_check: localhost:8080

Lambda snippet :
public class Handler implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> 

**Steps to reproduce**
Described above

**What did you expect to see?**
I would like to see the tracing/span payload and if not sending to collector.

**What did you see instead?**
Nothing useful.

**Environment**

  
receivers:
  otlp:
    protocols:
      http:
        #endpoint: otlphttp-blue.monitoring.comcast.net:4318
     
      grpc:
         #endpoint: otlpgrpc-blue.monitoring.comcast.net:4317

  

exporters:
  logging:
    loglevel: "debug"
  otlphttp:
    endpoint: https://abv:4318
   
  
    
service:
  telemetry:
    logs:
      level: "debug"
    
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlphttp]
      
     
    metrics:
      receivers: [otlp]
      exporters: [logging, otlphttp]
     

   

**Additional context**
LOGS

{
    "level": "info",
    "ts": 1686238886.230736,
    "caller": "service/service.go:146",
    "msg": "Everything is ready. Begin running and processing data."
}

**Comment by vasireddy99** [comment]
Thanks for providing the context, Can you please provide more on what lambda layer([Java-Agent](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java-auto-instr)/[Java-Wrapper](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java))  along with version used in the example or is it a [custom built lambda layer](https://github.com/open-telemetry/opentelemetry-lambda/blob/c6a7138f19999f2c0adb7b5752b263ad76581647/java/README.md#building). The logging exporter with `loglevel:debug` is good start to get more insights of debugging, as i see that is already present in config. Can you be able to add a reproducible example for us to look at and complete logs if possible incase you are still facing the issue?
