### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by choi258** [aws-observability/aws-otel-lambda#599]
Hi, 

We know AWS Lambda recently added support for Python 3.10, but can we get python 3.10 support for otel wrapper as well?
https://aws-otel.github.io/docs/getting-started/lambda/lambda-python

Thanks!

**Comment by vsakaram** [comment]
Thanks for raising this issue. This is on our radar and we plan to review this and we will keep this ticket updated.

**Comment by vasireddy99** [comment]
Hello, [python3.10](https://github.com/open-telemetry/opentelemetry-lambda/pull/778) is now supported in the [lambda layer](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python). Closing this issue. Thank you !
