### ISSUE TITLE
Documentation for S3 Confmap Provider is incorrect

### ISSUE THREAD

**Issue by karlpvoss** [aws-observability/aws-otel-lambda#608]
**Describe the bug**

The provided example for loading configuration for the collector from S3 is incorrect.

**Steps to reproduce**

Set a value for `OPENTELEMETRY_COLLECTOR_CONFIG_FILE` to a file in S3, using a `https` schema as documented, e.g. `https://<bucket_name>.s3.<region>.amazonaws.com/path/to/config.yaml`

https://aws-otel.github.io/docs/components/confmap-providers#s3-provider

<img width="672" alt="Screenshot 2023-06-16 at 14 20 09" src="https://github.com/aws-observability/aws-otel-lambda/assets/13564686/999f73aa-d6e7-45bc-841a-4a64eaa0c8af">

**What did you expect to see?**

That the configuration file is retrieved as expected.

**What did you see instead?**

```
{
    "level": "info",
    "ts": 1686845942.0120084,
    "msg": "done",
    "error": "failed to get config: cannot resolve the configuration: cannot retrieve the configuration: failed to load resource from uri \"https://REDACTED.s3.ap-southeast-2.amazonaws.com/otel/lambda/collector-config.yaml\". status code: 403; request failed with status 403 Forbidden",
    "errorCauses": [
        {
            "error": "failed to get config: cannot resolve the configuration: cannot retrieve the configuration: failed to load resource from uri \"https://REDACTED.s3.ap-southeast-2.amazonaws.com/otel/lambda/collector-config.yaml\". status code: 403"
        },
        {
            "error": "request failed with status 403 Forbidden"
        }
    ]
}
```

**Environment**

Deploying with the following environment variables:

```
OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318'
AWS_LAMBDA_EXEC_WRAPPER: '/opt/otel-handler'
OPENTELEMETRY_COLLECTOR_CONFIG_FILE: `https://REDACTED.s3.${region}.amazonaws.com/otel/lambda/collector-config.yaml`
  
```

**Additional context**

Changing the `https` scheme to `s3` works as expected.

**Comment by rapphil** [comment]
Hi, 

Does the lambda execution role have permission to access the bucket where the configuration is stored?

**Comment by karlpvoss** [comment]
Hey @rapphil, yes it does.

I have verified this by assuming the role and running a `aws s3 cp ...` and it works without issue. As noted above, the lambda runs without errors when i change the scheme from `https` to `s3`.

**Comment by rapphil** [comment]
you are right, the example in the documentation is incorrect. You have to use the schema `s3` for the s3 confmap provider to be used. Otherwise the `https` confmap provider will be used and since it will not have permission to access the bucket, the status code 403 is returned to the confmap.

I created this pull request to fix the documentation. https://github.com/aws-otel/aws-otel.github.io/pull/576

Thank you very much for opening this issue.

**Comment by karlpvoss** [comment]
Thanks mate, this one can be closed.
