### ISSUE TITLE
Documentation for included Processors is incorrect

### ISSUE THREAD

**Issue by karlpvoss** [aws-observability/aws-otel-lambda#609]
**Describe the bug**

Many Processors are documented as available and functional when this is not the case.

**Steps to reproduce**

Define any processor in the collector configuration file, e.g.

```
processors:
  tail_sampling:
    ...
```

**What did you expect to see?**

That the processors are functional, as documented here: https://aws-otel.github.io/docs/components/processors#processors-supported-by-adot-collector

**What did you see instead?**

```
"error": "failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:\n\n* error decoding 'processors': unknown type: \"tail_sampling\" for id: \"tail_sampling\" (valid values: [])"
```

This is backed up by this issue: https://github.com/aws-observability/aws-otel-lambda/issues/269

**Environment**

N/A

**Additional context**

N/A

**Comment by mhausenblas** [comment]
ADOT PM here. @karlpvoss thanks for raising this issue and to be clear: the Tail Sampling processor is not included in our Lambda distro (see https://github.com/aws-observability/aws-otel-lambda#adot-lambda-layer-available-components for what is included) and we do not plan to include it there, given its semantics and requirements.
