### ISSUE TITLE
node.js lambda -> aws-otel-lambda -> ADOT collector doesn't work

### ISSUE THREAD

**Issue by NathanNam** [aws-observability/aws-otel-lambda#627]
It seems node.js lambda -> aws-otel-lambda -> ADOT collector doesn't work at this moment. We tried the following combination:

- Runtime: Node.js 18.x
- Architecture: x86_64
- aws-otel-lambda: aws-otel-nodejs-amd64-ver-1-13-0

Interestingly, python lambda -> aws-otel-lambda -> ADOT collector works.

- Runtime: Python 3.8
- Architecture: x86_64
- aws-otel-lambda: aws-otel-python-amd64-ver-1-18-0

Given our experience with the python route, we believe there are some issues or bugs in the node.js route at this moment.

Is anyone able to use node.js lambda -> aws-otel-lambda -> ADOT collector? If so, could you share your working combination of runtime, architecture, and aws-otel-lambda?

**Comment by vsakaram** [comment]
Can you provide some additional details on the failure that is seen to help us triage/investigate this issue better?

**Comment by NathanNam** [comment]
@vsakaram Thanks for your response. I'm not sure whether you have access to this AWS support case (13151228451).

For Node.js, the automatic instrumentation (i.e. no code changes needed other than the steps outlined in https://aws-otel.github.io/docs/getting-started/lambda/lambda-js#enable-auto-instrumentation-for-your-lambda-function) is working as intended for **AWS SDK V2** clients/calls but **NOT** for **AWS SDK V3 clients/calls.**

The AWS Distro for OpenTelemetry Lambda Support For JavaScript does work to automatically instrument the AWS SDK for JavaScript V2 (see screenshot Node_SDK_v2_working.png). This was tested in both Node14.x and Node 16.x .
![image](https://github.com/aws-observability/aws-otel-lambda/assets/8757699/296731e0-a6e0-46eb-857e-5a626724fe65)

However, ADOT for JavaScript doesn't work to automatically instrument the AWS SDK for JavaScript v3 in Node.js 18.x.
![image](https://github.com/aws-observability/aws-otel-lambda/assets/8757699/22334b11-f2f2-4cbc-8223-57e0ebc52d83)

**Comment by NathanNam** [comment]
@vsakaram Do you need anything else from me?

**Comment by NathanNam** [comment]
@vsakaram Any updates on this one?

**Comment by paradisecy** [comment]
any updates on this. are you planning to support aws-sdk v3 with nodejs 18 ?

**Comment by NathanNam** [comment]
Any updates?

**Comment by NathanNam** [comment]
Has this issue been addressed?
