### ISSUE TITLE
nodejs spans not exported when upgrading aws otel lambda layer to 1.15.0

### ISSUE THREAD

**Issue by umarkhan17** [aws-observability/aws-otel-lambda#669]
When we use layer arn:......:aws-otel-nodejs-amd64-ver-**1-0-1:2** we are able to see the spans being exported, but when we use lambda layer arn:.......:aws-otel-nodejs-amd64-ver-**1-15-0:1** we are able to see the spans being exported.

We are using manual instrumentation.

**Comment by umarkhan17** [comment]
We are using node 18.x runtimes. Layers till version 1-7-0:1 or 2 works, anything after that just simply does not work.
Is node 18.x runtime not officially supported by the layer?

**Comment by vasireddy99** [comment]
Thanks for creating the issue, Can you provide more information on `:aws-otel-nodejs-amd64-ver-1-0-1:2`and `1-7-0:1/2` is working on nodejs18.x runtime. but `:aws-otel-nodejs-amd64-ver-1-15-0:1` is not working on `nodejs18.x` runtime. Is the question that the layer works on other runtimes `nodejs16.x` etc., but didn't work on `nodejs18.x` runtime?

**Comment by umarkhan17** [comment]
The layer after 1-7-0 didn’t work on either of the nodejs runtimes.

**Comment by umarkhan17** [comment]
The collector runs, but i do not see any spans being generated on console(console span exporter). I have verified this by using both auto & manual instrumentation.

**Comment by nicognaW** [comment]
I'm having the same problem with `aws-otel-nodejs-amd64-ver-1-15-0:2` and runtime `nodejs18.x`, I haven't tested any other versions of the layer or the runtime. I posted the issue here https://github.com/aws-observability/aws-otel-community/issues/672.

Please let me know if you have anything want me to try.
