### ISSUE TITLE
How to configure NodeJs auto-instrumentation to use tracecontext instead of xray?

### ISSUE THREAD

**Issue by umarkhan17** [aws-observability/aws-otel-lambda#676]
Is there a way to configure the layer to auto-instrument nodejs service and use W3C tracecontext instead of xray? I have tried adding environment variable to the lambda. 

OTEL_PROPAGATORS = "tracecontext,baggage"

but it did not work.

nodejs 18.x runtime
layer version 1-7-0:2

**Comment by rapphil** [comment]
Hi,

Can you clarify what is your use case? and what you want to achieve? 

Do you just need to receive requests with context in a different format?

**Comment by umarkhan17** [comment]
Yes. To be specific, traceparent is what i want.
