### ISSUE TITLE
Error invoking Lambda function after adding latest layer (1-28-1) for java

### ISSUE THREAD

**Issue by poprahul** [aws-observability/aws-otel-lambda#686]
I am using SAM template to deploy my java based lambda function, which gets triggered from api gateway. I update the layer version as per the doc. When I am trying to invoke my lambda function with api gateway using 'sam local start-api', I am getting error as below:

Docs: https://aws-otel.github.io/docs/getting-started/lambda/lambda-java-auto-instr
Layer version: "arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-java-agent-amd64-ver-1-28-1:1"
SAM version: SAM CLI, version 1.95.0
OS: Mac

Error:
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the GetLayerVersion operation: Invalid Layer name:
arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-java-agent-amd64-ver-1-28-1

**Comment by mhausenblas** [comment]
Does `sam local` support layers?

**Comment by poprahul** [comment]
Yes it does actually. https://aws.amazon.com/blogs/compute/working-with-aws-lambda-and-lambda-layers-in-aws-sam/
