### ISSUE TITLE
Documentation error in environment variable for the Lambda Layer

### ISSUE THREAD

**Issue by awsimaya** [aws-observability/aws-otel-lambda#8]
## Doc Issue

On this page, https://aws-otel.github.io/docs/getting-started/lambda,  under  [this section](https://aws-otel.github.io/docs/getting-started/lambda#enable-auto-instrumentation-for-your-lambda-function) the value of the environment variable  *AWS_LAMBDA_EXEC_WRAPPER* is missing the **d** in **adot** which makes host lambda function fail executing.

**Comment by wangzlei** [comment]
submit [PR](https://github.com/aws-otel/aws-otel.github.io/pull/72) to update the doc
