### ISSUE TITLE
docs: document of supported python version is old

### ISSUE THREAD

**Issue by WinterYukky** [aws-observability/aws-otel-lambda#806]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
Document of supported python version is old. It written as following message.
> The Lambda layer supports Python 3.8 and Python 3.9 Lambda runtimes. For more information about supported Python versions, see the [OpenTelemetry Python documentation](https://github.com/open-telemetry/opentelemetry-python/blob/master/README.md#supported-runtimes) and the package on [PyPi](https://pypi.org/project/opentelemetry-api/).

<img width="581" alt="image" src="https://github.com/aws-observability/aws-otel-lambda/assets/49480575/85206a8e-559f-49ee-881b-85af164a4c09">

https://aws-otel.github.io/docs/getting-started/lambda/lambda-python

Python 3.10 is supported now.
https://github.com/open-telemetry/opentelemetry-lambda/pull/778

**Steps to reproduce**
Access the document.
https://aws-otel.github.io/docs/getting-started/lambda/lambda-python

**What did you expect to see?**
Python support include 3.10.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version of collector/language SDK version did you use?**
Version: -

**What language layer did you use?**
Config: `Python`

**Additional context**
No.

**Comment by vasireddy99** [comment]
The python lambda layer now supports python 3.10 runtime, [doc is updated ](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python)
