### ISSUE TITLE
Which version of the collector image contains https://github.com/open-telemetry/opentelemetry-lambda/pull/310?

### ISSUE THREAD

**Issue by wushujames** [aws-observability/aws-otel-lambda#883]
I'm having difficulty tracing down when a change to https://github.com/open-telemetry/opentelemetry-lambda gets pulled into the ADOT layers.

I am currently using the collector layer aws-otel-collector-arm64-ver-0-70-0.

I am interested in the fix for https://github.com/open-telemetry/opentelemetry-lambda/pull/310

Do you know which version of the aws-otel-collector layer contains the fix for https://github.com/open-telemetry/opentelemetry-lambda/pull/310?

Thanks,
-James

**Comment by KimboTodd** [comment]
I know this is a specific question about a specific PR, but I'm here looking for similar info. If anyone can show us where to look for this information generally that would be amazing. Thanks!
