### ISSUE TITLE
mongodb spans not generated

### ISSUE THREAD

**Issue by jeusdi** [aws-observability/aws-otel-lambda#903]
**Describe the bug**
I've deployed a lambda attaching `arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-amd64-ver-1-32-0:1`.

No mongodb spans are generated when I run lambda on aws.

**Steps to reproduce**
1. Create a lambda attaching above layer and using java17 runtime.

**What did you expect to see?**
See mongodb spans as local docker collector.

**What did you see instead?**
MongoDb spans are now generated.

**What version of collector/language SDK version did you use?**
I've attached `arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-amd64-ver-1-32-0:1` layer.

**What language layer did you use?**
Config: `Java`

**Additional context**

**Comment by arun-annamalai** [comment]
Have you tried Java11? I am not sure if Java 17 is yet officially supported
