### ISSUE TITLE
Spans are broken if not using X-RAY

### ISSUE THREAD

**Issue by Sutty100** [aws-observability/aws-otel-lambda#924]
**Describe the bug**
I have Lambda A that calls Lambda B via http through API Gateway. The span is not joined and instead I end up with two separate traces when using any tool other than X-RAY

**Steps to reproduce**
Create a Java 11 Lambda. Disable active tracing. Use the latest layer:
arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-agent-amd64-ver-1-32-0:1

OpenTelemetry config pointed to X-RAY, Zipkin, ElasticAPM

Lambda A and B both use API Gateway with the Lambda Proxy integration

Send some requests

**What did you expect to see?**
A single trace across the two Lambdas in all 3 OpenTel compatiable tools.

**What did you see instead?**
A single trace in X-RAY ✅
Two separate not joined traces in Zipkin and ElasticAPM ❌

**What version of collector/language SDK version did you use?**
Version: 1-32-0

**What language layer did you use?**
Config: Java

**Comment by gshpychka** [comment]
Still relevant.

**Comment by Sutty100** [comment]
This remains an issue!
